package persistence.entities;
// Generated 29 mars 2021 à 17:39:56 by Hibernate Tools 5.4.27.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * TCategorie generated by hbm2java
 */
public class TCategorie implements java.io.Serializable {

	private BigInteger CIdcateg;
	private String CCodecateg;
	private String CLibellecateg;
	private Set TProduits = new HashSet(0);

	public TCategorie() {
	}

	public TCategorie(BigInteger CIdcateg) {
		this.CIdcateg = CIdcateg;
	}

	public TCategorie(BigInteger CIdcateg, String CCodecateg, String CLibellecateg, Set TProduits) {
		this.CIdcateg = CIdcateg;
		this.CCodecateg = CCodecateg;
		this.CLibellecateg = CLibellecateg;
		this.TProduits = TProduits;
	}

	public BigInteger getCIdcateg() {
		return this.CIdcateg;
	}

	public void setCIdcateg(BigInteger CIdcateg) {
		this.CIdcateg = CIdcateg;
	}

	public String getCCodecateg() {
		return this.CCodecateg;
	}

	public void setCCodecateg(String CCodecateg) {
		this.CCodecateg = CCodecateg;
	}

	public String getCLibellecateg() {
		return this.CLibellecateg;
	}

	public void setCLibellecateg(String CLibellecateg) {
		this.CLibellecateg = CLibellecateg;
	}

	public Set getTProduits() {
		return this.TProduits;
	}

	public void setTProduits(Set TProduits) {
		this.TProduits = TProduits;
	}

}
