package persistence.entities;
// Generated 29 mars 2021 à 17:39:56 by Hibernate Tools 5.4.27.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * TClient generated by hbm2java
 */
public class TClient implements java.io.Serializable {

	private BigInteger CIdclient;
	private String CLoginclient;
	private String CMotpasseclient;
	private String CNomclient;
	private String CPrenomclient;
	private String CCiviliteclient;
	private String CDatenaissanceclient;
	private String CNumeroadrclient;
	private String CCommuneadrclient;
	private String CVilleadrclient;
	private String CCpadrclient;
	private String CTelclient;
	private String CFaxclient;
	private String CGsmclient;
	private String CEmailclient;
	private Set TCommandes = new HashSet(0);

	public TClient() {
	}

	public TClient(BigInteger CIdclient) {
		this.CIdclient = CIdclient;
	}

	public TClient(BigInteger CIdclient, String CLoginclient, String CMotpasseclient, String CNomclient,
			String CPrenomclient, String CCiviliteclient, String CDatenaissanceclient, String CNumeroadrclient,
			String CCommuneadrclient, String CVilleadrclient, String CCpadrclient, String CTelclient, String CFaxclient,
			String CGsmclient, String CEmailclient, Set TCommandes) {
		this.CIdclient = CIdclient;
		this.CLoginclient = CLoginclient;
		this.CMotpasseclient = CMotpasseclient;
		this.CNomclient = CNomclient;
		this.CPrenomclient = CPrenomclient;
		this.CCiviliteclient = CCiviliteclient;
		this.CDatenaissanceclient = CDatenaissanceclient;
		this.CNumeroadrclient = CNumeroadrclient;
		this.CCommuneadrclient = CCommuneadrclient;
		this.CVilleadrclient = CVilleadrclient;
		this.CCpadrclient = CCpadrclient;
		this.CTelclient = CTelclient;
		this.CFaxclient = CFaxclient;
		this.CGsmclient = CGsmclient;
		this.CEmailclient = CEmailclient;
		this.TCommandes = TCommandes;
	}

	public BigInteger getCIdclient() {
		return this.CIdclient;
	}

	public void setCIdclient(BigInteger CIdclient) {
		this.CIdclient = CIdclient;
	}

	public String getCLoginclient() {
		return this.CLoginclient;
	}

	public void setCLoginclient(String CLoginclient) {
		this.CLoginclient = CLoginclient;
	}

	public String getCMotpasseclient() {
		return this.CMotpasseclient;
	}

	public void setCMotpasseclient(String CMotpasseclient) {
		this.CMotpasseclient = CMotpasseclient;
	}

	public String getCNomclient() {
		return this.CNomclient;
	}

	public void setCNomclient(String CNomclient) {
		this.CNomclient = CNomclient;
	}

	public String getCPrenomclient() {
		return this.CPrenomclient;
	}

	public void setCPrenomclient(String CPrenomclient) {
		this.CPrenomclient = CPrenomclient;
	}

	public String getCCiviliteclient() {
		return this.CCiviliteclient;
	}

	public void setCCiviliteclient(String CCiviliteclient) {
		this.CCiviliteclient = CCiviliteclient;
	}

	public String getCDatenaissanceclient() {
		return this.CDatenaissanceclient;
	}

	public void setCDatenaissanceclient(String CDatenaissanceclient) {
		this.CDatenaissanceclient = CDatenaissanceclient;
	}

	public String getCNumeroadrclient() {
		return this.CNumeroadrclient;
	}

	public void setCNumeroadrclient(String CNumeroadrclient) {
		this.CNumeroadrclient = CNumeroadrclient;
	}

	public String getCCommuneadrclient() {
		return this.CCommuneadrclient;
	}

	public void setCCommuneadrclient(String CCommuneadrclient) {
		this.CCommuneadrclient = CCommuneadrclient;
	}

	public String getCVilleadrclient() {
		return this.CVilleadrclient;
	}

	public void setCVilleadrclient(String CVilleadrclient) {
		this.CVilleadrclient = CVilleadrclient;
	}

	public String getCCpadrclient() {
		return this.CCpadrclient;
	}

	public void setCCpadrclient(String CCpadrclient) {
		this.CCpadrclient = CCpadrclient;
	}

	public String getCTelclient() {
		return this.CTelclient;
	}

	public void setCTelclient(String CTelclient) {
		this.CTelclient = CTelclient;
	}

	public String getCFaxclient() {
		return this.CFaxclient;
	}

	public void setCFaxclient(String CFaxclient) {
		this.CFaxclient = CFaxclient;
	}

	public String getCGsmclient() {
		return this.CGsmclient;
	}

	public void setCGsmclient(String CGsmclient) {
		this.CGsmclient = CGsmclient;
	}

	public String getCEmailclient() {
		return this.CEmailclient;
	}

	public void setCEmailclient(String CEmailclient) {
		this.CEmailclient = CEmailclient;
	}

	public Set getTCommandes() {
		return this.TCommandes;
	}

	public void setTCommandes(Set TCommandes) {
		this.TCommandes = TCommandes;
	}

}
