package persistence.entities;
// Generated 29 mars 2021 à 17:39:56 by Hibernate Tools 5.4.27.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * TCommandeId generated by hbm2java
 */
public class TCommandeId implements java.io.Serializable {

	private BigInteger CIdproduit;
	private BigInteger CIdclient;
	private BigInteger CQtecommande;
	private Date CDatecommande;
	private BigInteger CEtatcommande;

	public TCommandeId() {
	}

	public TCommandeId(BigInteger CIdclient) {
		this.CIdclient = CIdclient;
	}

	public TCommandeId(BigInteger CIdproduit, BigInteger CIdclient, BigInteger CQtecommande, Date CDatecommande,
			BigInteger CEtatcommande) {
		this.CIdproduit = CIdproduit;
		this.CIdclient = CIdclient;
		this.CQtecommande = CQtecommande;
		this.CDatecommande = CDatecommande;
		this.CEtatcommande = CEtatcommande;
	}

	public BigInteger getCIdproduit() {
		return this.CIdproduit;
	}

	public void setCIdproduit(BigInteger CIdproduit) {
		this.CIdproduit = CIdproduit;
	}

	public BigInteger getCIdclient() {
		return this.CIdclient;
	}

	public void setCIdclient(BigInteger CIdclient) {
		this.CIdclient = CIdclient;
	}

	public BigInteger getCQtecommande() {
		return this.CQtecommande;
	}

	public void setCQtecommande(BigInteger CQtecommande) {
		this.CQtecommande = CQtecommande;
	}

	public Date getCDatecommande() {
		return this.CDatecommande;
	}

	public void setCDatecommande(Date CDatecommande) {
		this.CDatecommande = CDatecommande;
	}

	public BigInteger getCEtatcommande() {
		return this.CEtatcommande;
	}

	public void setCEtatcommande(BigInteger CEtatcommande) {
		this.CEtatcommande = CEtatcommande;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCommandeId))
			return false;
		TCommandeId castOther = (TCommandeId) other;

		return ((this.getCIdproduit() == castOther.getCIdproduit()) || (this.getCIdproduit() != null
				&& castOther.getCIdproduit() != null && this.getCIdproduit().equals(castOther.getCIdproduit())))
				&& ((this.getCIdclient() == castOther.getCIdclient()) || (this.getCIdclient() != null
						&& castOther.getCIdclient() != null && this.getCIdclient().equals(castOther.getCIdclient())))
				&& ((this.getCQtecommande() == castOther.getCQtecommande())
						|| (this.getCQtecommande() != null && castOther.getCQtecommande() != null
								&& this.getCQtecommande().equals(castOther.getCQtecommande())))
				&& ((this.getCDatecommande() == castOther.getCDatecommande())
						|| (this.getCDatecommande() != null && castOther.getCDatecommande() != null
								&& this.getCDatecommande().equals(castOther.getCDatecommande())))
				&& ((this.getCEtatcommande() == castOther.getCEtatcommande())
						|| (this.getCEtatcommande() != null && castOther.getCEtatcommande() != null
								&& this.getCEtatcommande().equals(castOther.getCEtatcommande())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCIdproduit() == null ? 0 : this.getCIdproduit().hashCode());
		result = 37 * result + (getCIdclient() == null ? 0 : this.getCIdclient().hashCode());
		result = 37 * result + (getCQtecommande() == null ? 0 : this.getCQtecommande().hashCode());
		result = 37 * result + (getCDatecommande() == null ? 0 : this.getCDatecommande().hashCode());
		result = 37 * result + (getCEtatcommande() == null ? 0 : this.getCEtatcommande().hashCode());
		return result;
	}

}
