package persistence.entities;
// Generated 29 mars 2021 à 17:39:56 by Hibernate Tools 5.4.27.Final

/**
 * TCommande generated by hbm2java
 */
public class TCommande implements java.io.Serializable {

	private TCommandeId id;
	private TProduit TProduit;
	private TClient TClient;

	public TCommande() {
	}

	public TCommande(TCommandeId id, TClient TClient) {
		this.id = id;
		this.TClient = TClient;
	}

	public TCommande(TCommandeId id, TProduit TProduit, TClient TClient) {
		this.id = id;
		this.TProduit = TProduit;
		this.TClient = TClient;
	}

	public TCommandeId getId() {
		return this.id;
	}

	public void setId(TCommandeId id) {
		this.id = id;
	}

	public TProduit getTProduit() {
		return this.TProduit;
	}

	public void setTProduit(TProduit TProduit) {
		this.TProduit = TProduit;
	}

	public TClient getTClient() {
		return this.TClient;
	}

	public void setTClient(TClient TClient) {
		this.TClient = TClient;
	}

}
