package persistence.entities;
// Generated 29 mars 2021 à 17:39:56 by Hibernate Tools 5.4.27.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * TProduit generated by hbm2java
 */
public class TProduit implements java.io.Serializable {

	private BigInteger PIdproduit;
	private TCategorie TCategorie;
	private String PDesigproduit;
	private BigInteger PPuproduit;
	private BigInteger PQteproduit;
	private String PConfigproduit;
	private String PMarqueproduit;
	private String PModeleproduit;
	private Set TCommandes = new HashSet(0);

	public TProduit() {
	}

	public TProduit(BigInteger PIdproduit, TCategorie TCategorie) {
		this.PIdproduit = PIdproduit;
		this.TCategorie = TCategorie;
	}

	public TProduit(BigInteger PIdproduit, TCategorie TCategorie, String PDesigproduit, BigInteger PPuproduit,
			BigInteger PQteproduit, String PConfigproduit, String PMarqueproduit, String PModeleproduit,
			Set TCommandes) {
		this.PIdproduit = PIdproduit;
		this.TCategorie = TCategorie;
		this.PDesigproduit = PDesigproduit;
		this.PPuproduit = PPuproduit;
		this.PQteproduit = PQteproduit;
		this.PConfigproduit = PConfigproduit;
		this.PMarqueproduit = PMarqueproduit;
		this.PModeleproduit = PModeleproduit;
		this.TCommandes = TCommandes;
	}

	public BigInteger getPIdproduit() {
		return this.PIdproduit;
	}

	public void setPIdproduit(BigInteger PIdproduit) {
		this.PIdproduit = PIdproduit;
	}

	public TCategorie getTCategorie() {
		return this.TCategorie;
	}

	public void setTCategorie(TCategorie TCategorie) {
		this.TCategorie = TCategorie;
	}

	public String getPDesigproduit() {
		return this.PDesigproduit;
	}

	public void setPDesigproduit(String PDesigproduit) {
		this.PDesigproduit = PDesigproduit;
	}

	public BigInteger getPPuproduit() {
		return this.PPuproduit;
	}

	public void setPPuproduit(BigInteger PPuproduit) {
		this.PPuproduit = PPuproduit;
	}

	public BigInteger getPQteproduit() {
		return this.PQteproduit;
	}

	public void setPQteproduit(BigInteger PQteproduit) {
		this.PQteproduit = PQteproduit;
	}

	public String getPConfigproduit() {
		return this.PConfigproduit;
	}

	public void setPConfigproduit(String PConfigproduit) {
		this.PConfigproduit = PConfigproduit;
	}

	public String getPMarqueproduit() {
		return this.PMarqueproduit;
	}

	public void setPMarqueproduit(String PMarqueproduit) {
		this.PMarqueproduit = PMarqueproduit;
	}

	public String getPModeleproduit() {
		return this.PModeleproduit;
	}

	public void setPModeleproduit(String PModeleproduit) {
		this.PModeleproduit = PModeleproduit;
	}

	public Set getTCommandes() {
		return this.TCommandes;
	}

	public void setTCommandes(Set TCommandes) {
		this.TCommandes = TCommandes;
	}

}
